### ISSUE TITLE
RFE: display progress indicator for slow network or slow hosts

### ISSUE THREAD

**Issue by mprove** [ProjectMirador/mirador#3184] opened 2020-07-02 06:54 UTC
- load https://www.e-rara.ch/i3f/v20/11583123/manifest into https://mirador-dev.netlify.app/__tests__/integration/mirador/
- switch to thumbnail bar
- in the screenshot I've clicked on [13].
=> It takes way to long until the image is displayed. Obviously due to network/server latency. 

Suggestions:
a) Display a progress indicator so that the user knows that something is happening and stays calm and patient. Or use the tiny thumbnail to scale it up as a placeholder for the large view + display some progress indicator anyhow.
b) implement pre-caching for the likely next page

**Comment by cbeer** [comment] 2020-07-02 18:18
Duplicate of https://github.com/ProjectMirador/mirador/issues/1972.

**Closed by cbeer** 2020-07-02 18:18 UTC
Labels: Mirador3
