### ISSUE TITLE
Hide buttons during Window fullscreen mode

### ISSUE THREAD

**Issue by stanislavkostadinov** [ProjectMirador/mirador#751] opened 2016-02-05 09:06 UTC
One of the scenarios for buttons from the slots menu (add slot left, right ...) is inappropriate.
Scenario 1: When we use fullscreen mode from the main menu we call `document.fullscreenElement` and the whole document is visible is fullscreen mode. In this case, inserion of new slot is within the visible (visible in fullscreen mode) area.
Scenario 2: When we use the OSD fullscreen mode we call `OpenSeadragon.requestFullScreen(_this.parent.parent.element[0])` and only current OSD within the focused slot is visible. Buttons from the slots menu add new slot but it is outside the visible element and it is visible only if we exit the fullscreen mode.

**Comment by aeschylus** [comment] 2016-02-11 17:29
Agreed. We should remove or disable those buttons when the user enters single-window fullscreen mode.

**Comment by rsinghal** [comment] 2016-07-07 15:57
I think #1 is not a bug since you are simply making the entire Mirador application full screen, and someone might want to add more slots.  #2 is a bug and full screen should disable those particular buttons.

**Comment by rsinghal** [comment] 2016-07-08 16:15
@aeschylus I am running into a race condition while working on this bug.  I want to add some publish statements in [window.js](https://github.com/IIIF/mirador/blob/release2.1/js/src/workspaces/window.js#L818-L829) which will then be listened to by `workspace.js`, which would then publish information about what to hide based on the number of slots currently available in the application.  However, fullscreen toggles [d3's resize window event](https://github.com/IIIF/mirador/blob/release2.1/js/src/workspace.js#L107), which ultimately causes [the same events to be published](https://github.com/IIIF/mirador/blob/release2.1/js/src/workspace.js#L209-L213), overwriting any published events from `window.js` because they occur later.  Any thoughts on how to deal with this?

**Comment by regisrob** [comment] 2017-04-14 12:01
I find this bug quite annoying and misleading for users. Since the window layout menu is not usable in OSD fullscreen mode, it should always be disable in the window bar when fullscreen is on.

I have tried to fix that in a very simple way: https://github.com/regisrob/mirador/commit/ea8b802c073b52ac079888c6413d7d0d33d2fb8e
Tested on Windows 10 with FF 52.0.2 / Chrome 57.0.2987.133 / Edge 38.14393.1066.0, on the develop branch including the changes from [this PR](https://github.com/ProjectMirador/mirador/pull/1375) @c-alers (fix IE fullscreen)

@aeschylus @rsinghal Could you have a look at this commit and let me know if it is a good approach or not? If you think it is an acceptable solution, I could make a PR asap.

**Comment by rsinghal** [comment] 2017-04-18 14:28
I think this seems reasonable.  I looked back at my old code when I tried to fix this and was trying to do something more complex.  This solves the specific issue that needs to be fixed, so I think we should move forward with it.

**Comment by camillevilla** [comment] 2020-08-20 01:11
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

**Closed by camillevilla** 2020-08-20 01:11 UTC
Labels: bug, ui/ux
