### ISSUE TITLE
Annotation create: target=new window does not open new window, replaces active window

### ISSUE THREAD

**Issue by blalbrit** [ProjectMirador/mirador#1323] opened 2017-03-06 04:21 UTC
Description: if we add a new link with target=new window the link is not run in a new tab of the browser.

![1487684610463](https://cloud.githubusercontent.com/assets/796990/23596610/11537bb8-01e1-11e7-866e-1ebbbe9a436e.png)
![1487684661594](https://cloud.githubusercontent.com/assets/796990/23596611/1767a9de-01e1-11e7-806a-9dfce9a62320.png)
![1487684719093](https://cloud.githubusercontent.com/assets/796990/23596615/1d933a6c-01e1-11e7-8ded-68d15795c607.png)

**Comment by radpet** [comment] 2017-03-06 11:13
Are you using the latest release, since I cannot reproduce it on http://projectmirador.org/demo/

**Comment by blalbrit** [comment] 2017-03-06 14:44
Thanks @radpet - this was reported by a user we're working with, will try to reproduce on their configuration and update accordingly.

**Comment by camillevilla** [comment] 2020-09-03 16:49
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).

**Closed by camillevilla** 2020-09-03 16:49 UTC
Labels: 2017Sprint, Mirador2, annotations, bug, vatican
