### ISSUE TITLE
Drag and Drop not working in Safari

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador#1433] opened 2017-06-01 18:40 UTC
D&D works fine in Chrome and Firefox, but is currently broken in Safari (at least v10.1.1, macos 10.10.5)

In dropItem:

```
            var text_url = e.originalEvent.dataTransfer.getData("text/plain");
            if (text_url) {
                _this.handleDrop(text_url);
            } else {
                e.originalEvent.dataTransfer.items[0].getAsString(function(url) {
                    _this.handleDrop(url);
                });
            }
        }
```

When evaluating the e.originalEvent line, the error thrown is:

```
undefined is not an object (evaluating 'e.originalEvent ...')
```

**Comment by azaroth42** [comment] 2017-06-01 18:51
Debugging Info:

* e is an Event, with a originalEvent property 
* originalEvent is a MouseEvent, with a dataTransfer property
* dataTransfer is a DataTransfer, and does NOT have an items property.

It has files (FileList, length 0) and a long list of acceptable types.

Scanning through the event object and related objects the URL of the dropped manifest just doesn't appear.

The data Transfer in safari's debugger:
![screen shot 2017-06-01 at 11 50 22 am](https://cloud.githubusercontent.com/assets/871868/26695683/9260e712-46c0-11e7-9cd8-9911f73be899.png)

**Comment by azaroth42** [comment] 2017-06-01 19:00
(Verified by Michael Appleby YCBA and Charlie Butcosk Colby via IIIF Slack)

**Comment by schwemmer** [comment] 2017-06-16 17:59
If you drag from Firefox into Mirador in Safari, it works. When dragging from Chrome or Safari to Mirador in Safari it does not work. The same for IIIF Manifest Editor.

**Comment by yulgit1** [comment] 2017-11-01 13:49
Reproduced the above(D&D works fine in Chrome and Firefox, but is currently broken in Safari (at least v10.1.1, macos 10.10.5).  Looking at the API it appears this is because only chrome and firefox support DataTransformItems (how the manifest is currently transferred).  See "browser compatibility" section of:

https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem

Maybe there's an alternative mechanism for those browsers?

**Comment by yulgit1** [comment] 2017-11-01 14:59
Regarding:
e.originalEvent.dataTransfer.getData("text/plain")

This returns empty (firefox,chrome,safari).  Tried adding a draggable=true attribute and an ondragstart function around the iiif logo to drag with
ev.dataTransfer.setData("text", ev.target.href);
and also
ev.dataTransfer.setData("text/plain", ev.target.href);
Where ev.target.href is the URL to the manifest, but still an empty string on the getData side.

**Comment by philip-firstorder** [comment] 2019-05-03 15:38
I was able to reproduce this using this [codepen](https://codepen.io/philip-firstorder/pen/LoPNKg?editors=1111), here are the steps:

1. Open Safari, Chrome, Firefox, Opera browsers on the screen and paste the [codepen](https://codepen.io/philip-firstorder/pen/LoPNKg?editors=1111) link
2. Try dragging the text from Chrome, Firefox, Opera into the Safari box
3. Safari accepts only from Firefox or another Safari window
4. Open the codepen Console to see the getData contents

**Comment by camillevilla** [comment] 2020-09-10 20:14
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

**Closed by camillevilla** 2020-09-10 20:14 UTC
Labels: Mirador2
