### ISSUE TITLE
Bookmark and SaveController not working

### ISSUE THREAD

**Issue by c-alers** [ProjectMirador/mirador#1448] opened 2017-06-16 15:47 UTC
We've been developing off of the 2.2.0 version of Mirador. We recently attempted to use the Bookmark feature and ran into a few issues. The one we could not overcome was that saved state, when retrieved by the client through the "json=<boodmarkid>", would restore everything but the current canvas for each window. The data was there, and the viewer showed the right amount of grids. But they would always be empty instead of showing the canvas for the id given. We even switched to the default "LocalJSONBlobAPI" endpoint, but that did not change the results.  

We knew we were a few releases behind, so I decided to try this on the current develop and master branches. Now we don't even get to the point of saving the current state. Instead, JSON.stringify is complaining about "circular structure" when the current state is attempted to be saved. So there are potentionally 2 issues that need to be address in the current release:

1.) The current state is not savable to a JSON String
2.) When the saved state is retrieved, the viewer does not display the canvases. 

![image](https://user-images.githubusercontent.com/25848168/27234017-7ccb22da-5289-11e7-9dc0-fd18aedf653e.png)

**Comment by rsinghal** [comment] 2017-06-20 16:39
duplicate of #1441

**Comment by camillevilla** [comment] 2020-09-09 17:40
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

**Closed by camillevilla** 2020-09-09 17:40 UTC
Labels: Mirador2
