### ISSUE TITLE
Rectangle annotation tool logic breaks

### ISSUE THREAD

**Issue by ViktorRibchev** [ProjectMirador/mirador#1111] opened 2016-09-09 07:39 UTC
Rectangle annotation tool logic breaks when two of the borders are touching the canvas borders. 
Please see: 
[Mirador 1 logic.zip](https://github.com/IIIF/mirador/files/463391/Mirador.1.logic.zip)

**Comment by aeschylus** [comment] 2016-09-12 23:27
Reproducing it locally it looks like it's a problem with the "in-bounds" check. I'll try to have this fixed in the next day or so.

**Comment by aeschylus** [comment] 2016-09-12 23:27
Probably also the cause of #1110

**Comment by aeschylus** [comment] 2016-11-10 20:20
For anyone who can't download the zip and see the webm inside of it, you can reproduce this by entering annotation edit mode, and then beginning a rectangular annotation outside of the main image area. Dragging to expand the region will cause it to grow huge, outside the bounds of the image in both directions. This is controlled in this checking code referenced when a region's dimensions are updated: https://github.com/ProjectMirador/mirador/blob/ef670959a589843f4d598ac0c76a83a17f334001/js/src/annotations/osd-svg-overlay.js#L455-L478

However, The check doesn't seem to be being performed properly when the rectangle is initialised outside the canvas (image) boundary.

**Comment by mejackreed** [comment] 2016-11-16 18:37
I worked on this trying to solve the problem in several ways but was unsuccessful. Here are the approaches I tried:

 - modifying `adjustDeltaForShape` algorithm to snap to bounds when larger than it should be
 - reverting to old `adjustDeltaForShape` algorithm
 - adding a `snapToBounds` method that fired after frame change
 - `snapToBounds` try putting that in other parts of the event cycle
 - untold others

One comment @aeschylus made on slack seemed relevant. There seems to be a disconnect between the mouse events and the frame change. I hope someone else can figure this out, I'd be curious to how they solve.

**Comment by camillevilla** [comment] 2020-09-03 16:52
This ticket is being closed as part of the Mirador 3 issues review. We encourage all Mirador 2 implementers to try out Mirador 3 and leave feedback in new tickets.

In Mirador 3, annotation creation has been moved out of the core library and into [projectmirador/mirador-annotations](https://github.com/ProjectMirador/mirador-annotations).

**Closed by camillevilla** 2020-09-03 16:52 UTC
Labels: Mirador2, annotations
