### ISSUE TITLE
Annotation overlay fails to update after delete

### ISSUE THREAD

**Issue by gigamorph** [ProjectMirador/mirador#1131] opened 2016-09-20 18:50 UTC
This may also be related to #1103 but when I use an endpoint with an asynchronous API (as opposed to the local storage endpoint), Deleting an annotation from a tooltip editor will not cause the shape to disappear immediately. Only after I turn the annotation layer off and on again, it doesn't show any more.

Here are the screenshots of printouts (of published events) from the delete event in the two cases:

Local storage endpoint:
![m_core](https://cloud.githubusercontent.com/assets/86015/18684241/7a5f1702-7f41-11e6-891e-a4e46345fe84.png)

My custom endpoint (asynchronous):
![m_yale](https://cloud.githubusercontent.com/assets/86015/18684274/8d335c8a-7f41-11e6-901d-f688a0509564.png)

**Comment by rsinghal** [comment] 2016-09-20 19:07
Yup, it is the same issue as #1103 and #1126.  With local storage, `annotationListLoaded` is being published before `modeChange` and that order is not happening with your external storage.  Since order matters, we need to change how this information gets passed to the AnnotationsLayer

**Comment by rsinghal** [comment] 2016-09-20 19:09
Well #1103 is related, but slightly different.  #1126 and this one have the same ordering issue

**Comment by beaudet** [comment] 2016-11-15 16:33
Could not reproduce this within ConservationSpace.  ConservationSpace uses an alternative annotation editing dialogue and also pops up a confirmation message after delete is clicked.  Not sure if that has anything to do with why it cannot be reproduced in CS.  Is this bug in any way dependent upon the types or numbers of annotations created?  I did detect a bug where after saving an annotation after editing, hover over the next annotation doesn't produce the pop-up.  You have to hover off an then back on to see the pop-up.

**Comment by aeschylus** [comment] 2017-02-24 18:34
Also no longer able to reproduce. Closing this for now, but would be good to reference this issue again if it re-emerges.

**Closed by aeschylus** 2017-02-24 18:34 UTC
Labels: annotations, bug

**Comment by rsinghal** [comment] 2017-02-24 20:25
Which type of endpoint did you test this with?  Needs to be checked against LocalStorage and an asynchronous db.
