### ISSUE TITLE
Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by parksong22** [ProjectMirador/mirador#2601] opened 2019-05-03 20:19 UTC
I am having this issue for 3 days and I can't figure out what the problem is.
Basically, when I do `npm start`, it gives me this error.

> ERROR in ./src/components/AttributionPanel.js

    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: Cannot read property 'has' of undefined
        at resolvePath (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:22:24)
        at importModule (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\babel-plugin-lodash\lib\importModule.js:36:53)
        at memoized (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\memoize.js:62:23)
        at C:\Users\sp2273\Documents\GitHub\mirador\node_modules\babel-plugin-lodash\lib\index.js:203:62
        at arrayEach (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\forEach.js:38:10)
        at C:\Users\sp2273\Documents\GitHub\mirador\node_modules\babel-plugin-lodash\lib\index.js:193:30
        at arrayEach (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\forEach.js:38:10)
        at C:\Users\sp2273\Documents\GitHub\mirador\node_modules\babel-plugin-lodash\lib\index.js:181:28
        at arrayEach (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\_arrayEach.js:15:9)
        at forEach (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\lodash\forEach.js:38:10)
        at PluginPass.Program (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\babel-plugin-lodash\lib\index.js:170:26)
        at newFn (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\visitors.js:193:21)
        at NodePath._call (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\path\context.js:53:20)
        at NodePath.call (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\path\context.js:40:17)
        at NodePath.visit (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\path\context.js:88:12)
        at TraversalContext.visitQueue (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\context.js:118:16)
        at TraversalContext.visitSingle (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\context.js:90:19)
        at TraversalContext.visit (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\context.js:146:19)
        at Function.traverse.node (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\index.js:94:17)
        at traverse (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\traverse\lib\index.js:76:12)
        at transformFile (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\core\lib\transformation\index.js:88:29)
        at runSync (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\core\lib\transformation\index.js:45:3)
        at runAsync (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\core\lib\transformation\index.js:35:14)
        at process.nextTick (C:\Users\sp2273\Documents\GitHub\mirador\node_modules\@babel\core\lib\transform.js:34:34)
        at process._tickCallback (internal/process/next_tick.js:61:11)
     @ ./src/containers/AttributionPanel.js 1:278-339 9:463-479
     @ ./src/components/CompanionWindowFactory.js
     @ ./src/containers/CompanionWindowFactory.js
     @ ./src/components/CompanionArea.js
     @ ./src/containers/CompanionArea.js
     @ ./src/components/Window.js
     @ ./src/containers/Window.js
     @ ./src/components/Workspace.js
     @ ./src/containers/Workspace.js
     @ ./src/components/WorkspaceArea.js
     @ ./src/containers/WorkspaceArea.js
     @ ./src/components/App.js
     @ ./src/containers/App.js
     @ ./src/lib/MiradorViewer.js
     @ ./src/init.js
     @ ./src/index.js

Here's how my files look like:
package.json

> {
  "name": "mirador",
  "version": "3.0.0-alpha.6",
  "description": "",
  "main": "dist/mirador.min.js",
  "files": [
    "dist"
  ],
  "scripts": {
    "clean": "rm -rf ./dist",
    "lint": "node_modules/.bin/eslint ./ && node_modules/.bin/sass-lint -v ./src/styles/**/* && npm run lint:translations",
    "lint:translations": "node ./scripts/i18n-lint.js",
    "server": "node_modules/.bin/http-server",
    "test": "npm run build && npm run lint && npm run size && jest -c jest.json",
    "test:watch": "jest -c jest.json --watch",
    "build": "webpack --mode=production",
    "build:dev": "webpack --mode=development",
    "build:es": "mkdir -p dist/es && cp -r src dist/es && babel dist/es -d dist/es",
    "build:watch": "webpack --watch --mode=development",
    "prepublishOnly": "npm run clean && npm run build:es && npm run build",
    "size": "bundlewatch --config bundlewatch.config.json",
    "start": "npm run build:dev && concurrently \"npm run build:watch\" \"npm run server -- -p 4444\"",
    "server:json": "node ./scripts/json-server/server.js >> ./scripts/json-server/json-server.log"
  },
  "license": "Apache-2.0",
  "contributors": [
    "Drew Winget <scipioaffricanus@gmail.com> (https://aeschylus.net/)",
    "Jack Reed <phillipjreed@gmail.com> (https://www.jack-reed.com)"
  ],
  "repository": "https://github.com/ProjectMirador/mirador",
  "dependencies": {
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.2",
    "@researchgate/react-intersection-observer": "^0.7.4",
    "classnames": "^2.2.6",
    "css-ns": "^1.2.2",
    "deepmerge": "^3.1.0",
    "dompurify": "^1.0.9",
    "i18next": "^15.0.9",
    "immutable": "^4.0.0-rc.12",
    "intersection-observer": "^0.5.1",
    "lodash": "^4.17.11",
    "manifesto.js": "^3.0.9",
    "node-fetch": "^2.3.0",
    "node-sass": "^4.9.2",
    "normalize-url": "^4.2.0",
    "openseadragon": "^2.4.0",
    "prop-types": "^15.6.2",
    "react-copy-to-clipboard": "^5.0.1",
    "react-full-screen": "^0.2.4",
    "react-i18next": "^10.8.1",
    "react-iframe-comm": "^1.2.2",
    "react-image": "^2.1.1",
    "react-mosaic-component": "^2.1.0",
    "react-new-window": "0.0.12",
    "react-placeholder": "^3.0.1",
    "react-redux": "^7.0.0",
    "react-resize-observer": "^1.1.1",
    "react-rnd": "^9.1.1",
    "react-sizeme": "^2.5.2",
    "react-svg-unique-id": "^1.0.1",
    "react-virtualized-auto-sizer": "^1.0.2",
    "react-window": "^1.8.1",
    "redux": "4.0.1",
    "redux-devtools-extension": "^2.13.2",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "sass-loader": "^7.1.0",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.4.3",
    "@babel/core": "^7.4.4",
    "@babel/plugin-transform-runtime": "^7.4.3",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-react": "^7.0.0",
    "babel-eslint": "10.0.1",
    "babel-jest": "^24.7.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "bundlewatch": "^0.2.1",
    "chalk": "^2.4.2",
    "codecov": "^3.3.0",
    "concurrently": "^4.0.1",
    "css-loader": "^2.1.0",
    "enzyme": "^3.4.4",
    "enzyme-adapter-react-16": "^1.12.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-react-app": "^3.0.5",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-flowtype": "^3.6.1",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jest": "^22.4.1",
    "eslint-plugin-jsx-a11y": "^6.2.0",
    "eslint-plugin-react": "^7.12.4",
    "glob": "^7.1.3",
    "http-server": "^0.11.1",
    "jest": "^24.7.1",
    "jest-fetch-mock": "^2.1.2",
    "jest-puppeteer": "^4.1.1",
    "jsdom": "14.0.0",
    "json-server": "^0.14.2",
    "puppeteer": "^1.14.0",
    "react": "^16.8.6",
    "react-dev-utils": "^8.0.0",
    "react-dom": "^16.8.6",
    "redux-mock-store": "^1.5.1",
    "sass-lint": "^1.12.1",
    "style-loader": "^0.23.1",
    "supertest": "^4.0.2",
    "terser-webpack-plugin": "^1.2.1",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.1"
  },
  "peerDependencies": {
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
  }
}

webpack.config.js

> const path = require('path');
const webpack = require('webpack');
const paths = require('./config/paths');
const babelLoaderConfig = {
  include: paths.appSrc, // CRL
  loader: require.resolve('babel-loader'),
  options: {
    // Save disk space when time isn't as important
    cacheCompression: true,
    cacheDirectory: true,
    compact: true,
  },
  test: /\.(js|mjs|jsx)$/,
};
const baseConfig = [
  {
    entry: './src/index-core.js',
    module: {
      rules: [
        babelLoaderConfig,
      ],
    },
    output: {
      filename: 'm3core.umd.js',
      library: 'm3core',
      libraryTarget: 'umd',
      path: path.join(__dirname, 'dist'),
    },
  },
  {
    entry: './src/index.js',
    module: {
      rules: [
        babelLoaderConfig,
        {
          test: /\.s?css$/,
          use: [
            'style-loader', // creates style nodes from JS strings
            'css-loader', // translates CSS into CommonJS
            'sass-loader', // compiles Sass to CSS, using Node Sass by default
          ],
        },
      ],
    },
    output: {
      filename: 'mirador.min.js',
      library: 'Mirador',
      libraryExport: 'default',
      libraryTarget: 'umd',
      path: path.join(__dirname, 'dist'),
    },
    plugins: [
      new webpack.IgnorePlugin({
        resourceRegExp: /@blueprintjs\/(core|icons)/, // ignore optional UI framework dependencies
      }),
    ],
    resolve: { extensions: ['.js'] },
  },
];
module.exports = (env, options) => {
  const isProduction = options.mode === 'production';
  return baseConfig.map((config) => {
    config.devtool = !isProduction ? 'eval-source-map' : false; // eslint-disable-line no-param-reassign
    return config;
  });
};

.babelrc

> {
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "transform-react-remove-prop-types",
    ["lodash", { "id": [
      "lodash", "react-placeholder",
      ]}
    ]],
}

I tried many different things, but I couldn't resolve the issue.

node v10.15.3
npm v6.4.1
webpack v4
babel v7

Any idea?

**Comment by Sebi11** [comment] 2019-05-21 07:44
Hi!
I think this issue is a duplicate of https://github.com/ProjectMirador/mirador/issues/2599

**Closed** 2019-07-03 13:56 UTC
